document.write( '<noscript>\n' );
document.write( '        <p style=\'color:red;font-size: xx-large !important;\'>您的瀏覽器不支援JavaScript功能，若網頁功能無法正常使用時，請開啟瀏覽器JavaScript狀態</p>\n' );
document.write( '    </noscript>\n' );
document.write( '    <!-- 跳到主要內容區塊 -->\n' );
document.write( '    <div class=\"for_accessibility\">\n' );
document.write( '        <a href=\"#AC\" class=\"go-main\" title=\"跳到主要內容區塊\" tabindex=\"1\">跳到主要內容區塊</a>\n' );
document.write( '    </div>\n' );
document.write( '\n' );
document.write( '    <!-- 導覽列 -->\n' );
document.write( '    <div class=\"minibar\">\n' );
document.write( '        <div class=\"container\">\n' );
document.write( '            <a href=\"#U\" id=\"AU\" title=\"右上方功能區塊\" accesskey=\"U\" tabindex=\"2\">:::</a>\n' );
document.write( '            <a href=\"line.html\"><img src=\"img/line.png\" alt=\"line\"></a>\n' );
document.write( '            <a href=\"webmap.html\"><img src=\"img/webmap.png\" alt=\"webmap\"></a>\n' );
document.write( '            <a href=\"https://iotmanage.wra.gov.tw/\"><img src=\"img/backend.png\" alt=\"backend\"></a>\n' );
document.write( '            <div class=\"btn\">\n' );
document.write( '                <ul>\n' );
document.write( '                    <li><a href=\"login.html\">登入</a></li>\n' );
document.write( '                    <li>|</li>\n' );
document.write( '                    <li><a href=\"sign-up.html\">註冊</a></li>\n' );
document.write( '                </ul>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '\n' );
document.write( '    </div>\n' );
document.write( '    <nav class=\"navbar\">\n' );
document.write( '        <div class=\"pc\">\n' );
document.write( '            <div class=\"navbar-L\">\n' );
document.write( '                <a href=\"index.html\">\n' );
document.write( '                    <img src=\"img/logo.jpg\" alt=\"logo\">\n' );
document.write( '                </a>\n' );
document.write( '            </div>\n' );
document.write( '            <div class=\"navbar-R\">\n' );
document.write( '                <div class=\"nav-function\">\n' );
document.write( '                    <a href=\"\">\n' );
document.write( '                        <div class=\"title\">水資源競賽</div>\n' );
document.write( '                    </a>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"nav-function\">\n' );
document.write( '                    <a href=\"#\">\n' );
document.write( '                        <div class=\"title\">資料展示</div>\n' );
document.write( '                    </a>\n' );
document.write( '                    <div class=\"nav-list\">\n' );
document.write( '                        <a href=\"display-flood.html\">\n' );
document.write( '                            <div class=\"title\">都市淹水感知器</div>\n' );
document.write( '                        </a><br>\n' );
document.write( '                        <a href=\"display-river.html\">\n' );
document.write( '                            <div class=\"title\">河川水位站</div>\n' );
document.write( '                        </a><br>\n' );
document.write( '                        <a href=\"reservoir-info.html\">\n' );
document.write( '                            <div class=\"title\">水庫情資</div>\n' );
document.write( '                        </a><br>\n' );
document.write( '                        <a href=\"water-info.html\">\n' );
document.write( '                            <div class=\"title\">供水情資</div>\n' );
document.write( '                        </a>\n' );
document.write( '                    </div>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"nav-function\">\n' );
document.write( '                    <a href=\"#\">\n' );
document.write( '                        <div class=\"title\">開發指引</div>\n' );
document.write( '                    </a>\n' );
document.write( '                    <div class=\"nav-list\">\n' );
document.write( '                        <a href=\"api-explain.html\">\n' );
document.write( '                            <div class=\"title\">線上API說明</div>\n' );
document.write( '                        </a><br>\n' );
document.write( '                        <a href=\"example-code.html\">\n' );
document.write( '                            <div class=\"title\">範例程式碼</div>\n' );
document.write( '                        </a><br>\n' );
document.write( '                        <a href=\"data-explain.html\">\n' );
document.write( '                            <div class=\"title\">資料使用說明</div>\n' );
document.write( '                        </a><br>\n' );
document.write( '                    </div>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"nav-function\">\n' );
document.write( '                    <a href=\"#\">\n' );
document.write( '                        <div class=\"title\">分享專區</div>\n' );
document.write( '                    </a>\n' );
document.write( '                    <div class=\"nav-list\">\n' );
document.write( '                        <a href=\"example-all.html\">\n' );
document.write( '                            <div class=\"title\">相關連結</div>\n' );
document.write( '                        </a><br>\n' );
document.write( '                        <a href=\"resources-share.html\">\n' );
document.write( '                            <div class=\"title\">資源分享</div>\n' );
document.write( '                        </a><br>\n' );
document.write( '                    </div>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"nav-function\">\n' );
document.write( '                    <a href=\"#\">\n' );
document.write( '                        <div class=\"title\">作業規範</div>\n' );
document.write( '                    </a>\n' );
document.write( '                    <div class=\"nav-list\">\n' );
document.write( '                        <a href=\"rules.html\">\n' );
document.write( '                            <div class=\"title\">作業規範</div>\n' );
document.write( '                        </a><br>\n' );
document.write( '                        <a href=\"rules-example.html\">\n' );
document.write( '                            <div class=\"title\">參考典範指引</div>\n' );
document.write( '                        </a><br>\n' );
document.write( '                        <a href=\"rules-data.html\">\n' );
document.write( '                            <div class=\"title\">資料交換標準</div>\n' );
document.write( '                        </a><br>\n' );
document.write( '                        <a href=\"rules-domain.html\">\n' );
document.write( '                            <div class=\"title\">領域資料標準</div>\n' );
document.write( '                        </a>\n' );
document.write( '                    </div>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"nav-function\">\n' );
document.write( '                    <a href=\"science-classroom.html\">\n' );
document.write( '                        <div class=\"title\">科普小教室</div>\n' );
document.write( '                    </a>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"nav-function\">\n' );
document.write( '                    <a href=\"#\">\n' );
document.write( '                        <div class=\"title\">支援服務</div>\n' );
document.write( '                    </a>\n' );
document.write( '                    <div class=\"nav-list\">\n' );
document.write( '                        <a href=\"opinion.html\">\n' );
document.write( '                            <div class=\"title\">意見反映</div>\n' );
document.write( '                        </a><br>\n' );
document.write( '                        <a href=\"FAQ.html\">\n' );
document.write( '                            <div class=\"title\">FAQ</div>\n' );
document.write( '                        </a>\n' );
document.write( '                    </div>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"nav-function\">\n' );
document.write( '                    <a href=\"#\">\n' );
document.write( '                        <div style=\"margin-right: 0px;\" class=\"title\">會員專區</div>\n' );
document.write( '                    </a>\n' );
document.write( '                    <div class=\"nav-list\">\n' );
document.write( '                        <a href=\"member-data.html\">\n' );
document.write( '                            <div class=\"title\">會員資料修改</div>\n' );
document.write( '                        </a><br>\n' );
document.write( '                        <a href=\"api-attestation.html\">\n' );
document.write( '                            <div class=\"title\">API認證資訊</div>\n' );
document.write( '                        </a>\n' );
document.write( '                    </div>\n' );
document.write( '                </div>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"mobile\">\n' );
document.write( '            <div class=\"menu\">\n' );
document.write( '                <div class=\"fas fa-bars\" role=\"button\" tabindex=\"0\" aria-label=\"開啟選單\" aria-controls=\"main-menu\"\n' );
document.write( '                    aria-expanded=\"false\">\n' );
document.write( '                </div>\n' );
document.write( '                <ul class=\"nav navbar-nav\" id=\"main-menu\" aria-hidden=\"true\">\n' );
document.write( '                    <li class=\"nav-item dropdown\">\n' );
document.write( '                        <a class=\"nav-link dropdown-toggle\" href=\"javascript:void(0);\" data-toggle=\"dropdown\"\n' );
document.write( '                            aria-haspopup=\"true\" aria-expanded=\"false\">\n' );
document.write( '                            資料展示\n' );
document.write( '                        </a>\n' );
document.write( '                        <div class=\"dropdown-menu shadow-lg\">\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"display-flood.html\">\n' );
document.write( '                                <div class=\"title\">都市淹水感知器</div>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"display-river.html\">\n' );
document.write( '                                <div class=\"title\">河川水位站</div>\n' );
document.write( '                            </a>\n' );
document.write( '                        </div>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li class=\"nav-item dropdown\">\n' );
document.write( '                        <a class=\"nav-link dropdown-toggle\" href=\"javascript:void(0);\" data-toggle=\"dropdown\"\n' );
document.write( '                            aria-haspopup=\"true\" aria-expanded=\"false\">\n' );
document.write( '                            開發指引\n' );
document.write( '                        </a>\n' );
document.write( '                        <div class=\"dropdown-menu shadow-lg\">\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"theme.html\">\n' );
document.write( '                                <div class=\"title\">資料主題</div>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"api-explain.html\">\n' );
document.write( '                                <div class=\"title\">線上API說明</div>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"example-code.html\">\n' );
document.write( '                                <div class=\"title\">範例程式碼</div>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"data-explain.html\">\n' );
document.write( '                                <div class=\"title\">資料使用說明</div>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"data-statistics.html\">\n' );
document.write( '                                <div class=\"title\">資料使用統計</div>\n' );
document.write( '                            </a>\n' );
document.write( '                        </div>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li class=\"nav-item dropdown\">\n' );
document.write( '                        <a class=\"nav-link dropdown-toggle\" href=\"javascript:void(0);\" data-toggle=\"dropdown\"\n' );
document.write( '                            aria-haspopup=\"true\" aria-expanded=\"false\">\n' );
document.write( '                            分享專區\n' );
document.write( '                        </a>\n' );
document.write( '                        <div class=\"dropdown-menu shadow-lg\">\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"example-all.html\">\n' );
document.write( '                                <div class=\"title\">相關連結</div>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"resources-share.html\">\n' );
document.write( '                                <div class=\"title\">資源分享</div>\n' );
document.write( '                            </a>\n' );
document.write( '                        </div>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li class=\"nav-item dropdown\">\n' );
document.write( '                        <a class=\"nav-link dropdown-toggle\" href=\"javascript:void(0);\" role=\"button\"\n' );
document.write( '                            data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n' );
document.write( '                            作業規範\n' );
document.write( '                        </a>\n' );
document.write( '                        <div class=\"dropdown-menu shadow-lg\">\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"rules.html\">\n' );
document.write( '                                <div class=\"title\">作業規範</div>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"rules-example.html\">\n' );
document.write( '                                <div class=\"title\">參考典範指引</div>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"rules-data.html\">\n' );
document.write( '                                <div class=\"title\">資料交換標準</div>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"rules-domain.html\">\n' );
document.write( '                                <div class=\"title\">領域資料標準</div>\n' );
document.write( '                            </a>\n' );
document.write( '                        </div>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li class=\"nav-item dropdown\">\n' );
document.write( '                        <a href=\"science-classroom.html\">\n' );
document.write( '                            科普小教室\n' );
document.write( '                        </a>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li class=\"nav-item dropdown\">\n' );
document.write( '                        <a class=\"nav-link dropdown-toggle\" href=\"javascript:void(0);\" role=\"button\"\n' );
document.write( '                            data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n' );
document.write( '                            支援服務\n' );
document.write( '                        </a>\n' );
document.write( '                        <div class=\"dropdown-menu shadow-lg\">\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"opinion.html\">\n' );
document.write( '                                <div class=\"title\">意見反映</div>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"FAQ.html\">\n' );
document.write( '                                <div class=\"title\">FAQ</div>\n' );
document.write( '                            </a>\n' );
document.write( '                        </div>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li class=\"nav-item dropdown\">\n' );
document.write( '                        <a class=\"nav-link dropdown-toggle\" href=\"javascript:void(0);\" role=\"button\"\n' );
document.write( '                            data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n' );
document.write( '                            會員專區\n' );
document.write( '                        </a>\n' );
document.write( '                        <div class=\"dropdown-menu shadow-lg\">\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"member-data.html\">\n' );
document.write( '                                <div class=\"title\">會員資料修改</div>\n' );
document.write( '                            </a>\n' );
document.write( '                            <a class=\"dropdown-item\" href=\"api-attestation.html\">\n' );
document.write( '                                <div class=\"title\">API認證資訊</div>\n' );
document.write( '                            </a>\n' );
document.write( '                        </div>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li><a href=\"webmap.html\">網站導覽</a></li>\n' );
document.write( '                    <li><a href=\"line.html\">交談機器人</a></li>\n' );
document.write( '                    <li><a href=\"login.html\">登入</a></li>\n' );
document.write( '                    <li><a href=\"sign-up.html\">註冊</a></li>\n' );
document.write( '                </ul>\n' );
document.write( '            </div>\n' );
document.write( '            <div class=\"logo\">\n' );
document.write( '                <a href=\"index.html\">\n' );
document.write( '                    <img src=\"img/logo.jpg\" alt=\"logo\">\n' );
document.write( '                </a>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '    </nav>' );
